[build]
  functions = 'functions'
  publish = 'storage/app/static'
  command = 'sed -i "s|TOKEN_PLACEHOLDER|${OHSEESNAPS_TOKEN}|g" netlify.toml && npm run production && composer install && php please search:update default && php please ssg:generate'

[[headers]]
  for = "/feed"
  [headers.values]
	  Content-Type = "application/rss+xml"

[[redirects]]
  from = "/snap"
  to = "https://ohseesnaps.com/api/snap?token=TOKEN_PLACEHOLDER"
  force = true
  status = 301

[[redirects]]
  from = "/goals"
  to = "/posts/goals-for-2021"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404